### ISSUE TITLE
Need help with setting up the script. Getting errors.

### ISSUE THREAD

**Issue by stoicsystem** [enjoysmath/bootstrap-studio-to-django-template#6]
```
FileNotFoundError: [Errno 2] No such file or directory: 'E:/projects/designs/.bss-to-django-config.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bss_to_django.py", line 22, in <module>
  File "dialog\main_window.py", line 153, in try_loading_config_from_arg
  File "dialog\main_window.py", line 24, in __init__
  File "dialog\main_window.py", line 51, in finish_setup
  File "ntpath.py", line 670, in relpath
ValueError: path is on mount 'E:', start on mount 'C:'
```

I even moved the export script into the same drive as the designs. What is the issue over here?

**Comment by FruitfulApproach** [comment]
@stoicsystem  I noticed that when I put my code in GitHub document folder (default for GH desktop) I had some file descriptor troubles with the app.  So I recommend this total structure (which works for me):

C:\Users\Fruit\OneDrive\Desktop\Code\WebDev\
-      BootstrapStudioToDjango (cloned local repo; don't use release!!!)
-      MyDjangoProject (this folder contains manage.py)
-      BSSExport (intermediate folder specified to BSS in Export settings)

Then follow these instructions as I do to use it:

1. Open up your .bss design (I keep mine in MyDjangoProject folder as it's pretty safe to).
2. Make changes.
3. Change export settings to match mine:

![image](https://github.com/user-attachments/assets/b8a3790e-7fe8-401d-89ff-a68bd26f2055)

There might be some leeway here, but just know that some of these options can break the process.

4.  On the same Export settings dialog change your BSSExport folder to:

![image](https://github.com/user-attachments/assets/94b15a41-d6f9-4d52-91b1-3958503b66e6)

5.  Click save, then click somewhere in BSS.  Then Save your .bss design.  Click Export.
6. The export script should have run, but if not, talk to me. 

>  _It might currently need WingWare 101 at least (free) to run, possibly even Pro, the way I have the debug hook in there.  Btw this is nice if you want to help debug.  You just setup the DEBUGGER_PATH.txt file.  Then to debug an export issue, you run as usual, and it will pop into WingWare in debug mode when an exception occurs!  This is actually quite useful and amazing 🤩_

7. Next, go to the first tab of the Export script GUI and enter in (browse for) your MyDjangoProject directory (the folder).   Now on the Export Mapping tab, click "Check for BSS Changes", then "Expand Whole Tree".  Make sure everything looks legit _(note that code gen features are not completed in this, so some items on the RHS of the Export Mapping table will probably break.)_

8.  Click Run Exporter.  
_It should complete without errors, but I noticed some weird chars appearing in some of the default BSS templates, so I created my current site from scratch (blank BSS template)._

9. Click the Close Button [X] in the upper right of the app's main dialog.   This will save your settings to a .pkl file in BSSExport.  Should something go wrong, you could always delete this .pkl file to start over.

10.  Make changes and repeat the process.

**Comment by FruitfulApproach** [comment]
@stoicsystem notice that I use dev_bss_to_django.exe and not the release one.  This is for the best (and is much faster for reasons of PyToEXE cludginess), and will help us find bugs.   The [...]dev.exe simply launches the Python file.  So it is presumed that you have latest Python 3.xy on your Path.

I apologize for the late response on this!  Did you ever find a workaround of your own?

**Comment by FruitfulApproach** [comment]
@stoicsystem Fixed a bullshit char encoding error because BSS likes to output some weird shit sometimes.  So everything encodes/decodes with BeautifulSoup and file read/write using UTF8.  Should get rid of those nasty/weird space character errors both when converting to Django templates and when your site is run.  What a flimsy shitstack!  [/rant over]
